### ISSUE TITLE
 little doubt about private attribute with DI in component: LessonsCatalogComponent

### ISSUE THREAD

**Issue by ac4mm** [dsebastien/ngrx-component-store-demo#1]
https://github.com/dsebastien/ngrx-component-store-demo/blob/9f576cb2b6e0b47c80260616da09c81e569ada08/src/app/lessons-catalog/lessons-catalog.component.ts#L46

Hi mate, great repo but i have a struggled doubt about this line. How works if the template can't see _private_ attribute in component? Should it be _public_, right? Then transpiled the typeScript, javaScript shouldn't see the private attribute. I think this is a ng's bug, but i don't really much sure. I hope you will give me some right clarifications.
__
Thanks

**Comment by dsebastien** [comment]
Hello @ac4mm 

Indeed, it should actually be public. I'll update the article to fix this. I'm so used to put everything private that sometimes I'm over-enthusiastic ;-)
